# Generated by Django 2.2.28 on 2023-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPTPrompt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("system_message_template", models.TextField()),
                ("human_message_template", models.TextField()),
                ("key", models.CharField(max_length=100, unique=True)),
                ("model", models.IntegerField(choices=[(0, "gpt-4"), (1, "gpt-3.5-turbo")], default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
